config/routes.rb
Fitjar::Application.routes.draw do
  
  get "withdraws/new_release" => 'withdraws#new_release', :as => :new_release

  resources :banks do
  resources :withdraws

end

  resources :devices
  resources :charges

authenticated :user do
  root :to => "challenges#index"
end
unauthenticated :user do
  devise_scope :user do 
    get "/" => "pages#home"
  end
end

  devise_for :users
  resources :challenges do
    resources :questions, except: [:show, :index]
    resources :comments, :only => [:create, :destroy]

    resources :payments, only: [:new, :create]
  end

  get 'faq' => 'pages#faq'
  get 'about' => 'pages#about'
  get 'challenges' => 'challenges#index'
  get 'rules' => 'pages#rules'
  get 'home' => 'pages#home'
  get 'host' => "challenges#host"
  get 'terms' => "pages#terms"
  get 'history' => "payments#history"

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	belongs_to :user
	has_many :withdraws
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

 
  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)
    @bank.user_id = current_user.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    recipient = Stripe::Recipient.create(
      :name => current_user.full_name,
      :type => "individual",
      :bank_account => token
      )

    @bank.recipient_id = recipient.id


#stripe credit card payment begins
   
    
#stripe bank transfer > insert expression here:  if @challengewinner=Y, $ pushes into the user's balance summation of credit card charge amount)  #2 challenge stake+challenge stake

    current_user.save
    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bank }
      else
        format.html { render action: 'new' }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:bank)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<div class="container">
    <div class="container" style="max-width:400px; margin: 0 auto 10px;">

<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
          <div class="form-group">
            <%= f.label :bank %><br>
            <%= f.text_field :bank, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :country %>
            <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
          </div>
          <div class="form-group">
            <%= label_tag :routing_number %>
            <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
          </div>
          <div class="form-group">
            <%= label_tag :account_number %>
            <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
          </div>

          <div class="actions">
            <%= f.submit class: "btn btn-primary btn-block" %>
          </div>
<% end %>

  </div>
    </div>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<div class = "container">
  <h1>Listing banks</h1>

  <table>
    <thead>
      <tr>
        <th>Bank</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @banks.each do |bank| %>
        <tr>
          <td><%= bank.bank %></td>
          <td><%= link_to 'Show', bank %></td>
          <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
          <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Bank', new_bank_path %>
</div>

app/views/banks/new.html.erb
<h1 class = "center">New bank</h1>

<%= render 'form' %>



<div class = "container">
	<ul class= "pager">
           <li class="previous"><%= link_to "&larr; Back".html_safe, banks_path %></li>
      </ul>

 </div>

app/views/banks/new_release.js.erb
$("#modal-window").html("<%= escape_javascript(render 'project/new_release') %>");

app/views/banks/show.html.erb
<p>
  <strong>Bank:</strong>
  <%= @bank.bank %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>