config/routes.rb
Fitjar::Application.routes.draw do
  
  get "withdraws/new_release" => 'withdraws#new_release', :as => :new_release

  resources :banks do
  resources :withdraws

end

  resources :devices
  resources :charges

authenticated :user do
  root :to => "challenges#index"
end
unauthenticated :user do
  devise_scope :user do 
    get "/" => "pages#home"
  end
end

  devise_for :users
  resources :challenges do
    resources :questions, except: [:show, :index]
    resources :comments, :only => [:create, :destroy]

    resources :payments, only: [:new, :create]
  end

  get 'faq' => 'pages#faq'
  get 'about' => 'pages#about'
  get 'challenges' => 'challenges#index'
  get 'rules' => 'pages#rules'
  get 'home' => 'pages#home'
  get 'host' => "challenges#host"
  get 'terms' => "pages#terms"
  get 'history' => "payments#history"

end

app/models/withdraw.rb
class Withdraw < ActiveRecord::Base

belongs_to :user
belongs_to :bank

end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController
  before_action :set_withdraw, only: [:show, :edit, :update, :destroy]

  # GET /withdraws
  # GET /withdraws.json
  def index
    @withdraws = Withdraw.all
  end

  # GET /withdraws/1
  # GET /withdraws/1.json
  def show
  end

  # GET /withdraws/new
  def new
    @withdraw = Withdraw.new
    @bank = Bank.find(params[:bank_id])
  end

  # GET /withdraws/1/edit
  def edit
  end
  
  
  # POST /withdraws
  # POST /withdraws.json
  def create
    @withdraw = Withdraw.new(withdraw_params)
    #@withdraw = current_user.id
    @bank = Bank.find(params[:bank_id])
    @withdraw.bank_id = @bank.id

   Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    
#stripe bank transfer > insert expression here:  if @challengewinner=Y, $ pushes into the user's balance summation of credit card charge amount)  #2 challenge stake+challenge stake

 transfer = Stripe::Transfer.create(
      :amount => 500000,
      :currency => "usd",
      :recipient => @bank.recipient_id
      )

    @withdraw.user_id = current_user.id

#stripe credit card payment begins
  

    respond_to do |format|
      if @withdraw.save
        format.html { redirect_to @bank, notice: 'Withdraw was successfully created.' }
        format.json { render action: 'show', status: :created, location: @withdraw }
      else
        format.html { render action: 'new' }
        format.json { render json: @withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /withdraws/1
  # PATCH/PUT /withdraws/1.json
  def update
    respond_to do |format|
      if @withdraw.update(withdraw_params)
        format.html { redirect_to @withdraw, notice: 'Withdraw was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /withdraws/1
  # DELETE /withdraws/1.json
  def destroy
    @withdraw.destroy
    respond_to do |format|
      format.html { redirect_to withdraws_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_withdraw
      @withdraw = Withdraw.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def withdraw_params
      params.require(:withdraw).permit(:amount)
    end
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/withdraws/_form.html.erb
<div class="container" style="max-width:400px; margin: 0 auto 10px;">
  <%= form_for([@bank, @withdraw]) do |f| %>
    <% if @withdraw.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@withdraw.errors.count, "error") %> prohibited this withdraw from being saved:</h2>

        <ul>
        <% @withdraw.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<br><br>
          <div class="field">
            <%= f.label :amount%><br>
            <%= f.number_field :amount, class: "form-control"  %>
          </div>
<br>
          <div class="actions">
            <%= f.submit class: "btn btn-primary btn-block" %>
          </div>
  <% end %>
</div>

app/views/withdraws/edit.html.erb
<h1>Editing withdraw</h1>

<%= render 'form' %>

app/views/withdraws/index.html.erb
<div class = "container">

  <h1>Listing withdraws</h1>

  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @withdraws.each do |withdraw| %>
        <tr>
          <td><%=withdraw.amount %></td>
       
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New withdraw', new_bank_withdraw_path, data: { no_turbolink: true } %>
  <br>

</div>

app/views/withdraws/new.html.erb
<h1 class = "center">New withdraw</h1>

<%= render 'form' %>

<br><br><br><br><br><br><br><br><br><br><br><br>

app/views/withdraws/show.html.erb
<div class = "container">
	<p>
	  <strong>Amount:</strong>
	  <%= @withdraw.amount %>
	</p>


	<%= link_to 'Edit', edit_withdraw_path(@withdraw) %> |
	<%= link_to 'Back', withdraws_path %>

</div>