config/routes.rb
Fitjar::Application.routes.draw do
  
  get "withdraws/new_release" => 'withdraws#new_release', :as => :new_release

  resources :banks do
  resources :withdraws

end

  resources :devices
  resources :charges

authenticated :user do
  root :to => "challenges#index"
end
unauthenticated :user do
  devise_scope :user do 
    get "/" => "pages#home"
  end
end

  devise_for :users
  resources :challenges do
    resources :questions, except: [:show, :index]
    resources :comments, :only => [:create, :destroy]

    resources :payments, only: [:new, :create]
  end

  get 'faq' => 'pages#faq'
  get 'about' => 'pages#about'
  get 'challenges' => 'challenges#index'
  get 'rules' => 'pages#rules'
  get 'home' => 'pages#home'
  get 'host' => "challenges#host"
  get 'terms' => "pages#terms"
  get 'history' => "payments#history"

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	  

  #JQ - THIS IS FOR JARS FOR ARENA LATER, JUST COMMENT OUT FOR NOW, USE PROFILE PICTURE FOR DEVISE

    if Rails.env.development?
      has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "https://dl.dropboxusercontent.com/s/sm3ja2rreztsaj4/blue_dropbox_glyph-vflJ8-C5d.jpg"
    else
      has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "https://dl.dropboxusercontent.com/s/sm3ja2rreztsaj4/blue_dropbox_glyph-vflJ8-C5d.jpg",
          :storage => :dropbox,
          :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
          :path => ":style/:id_:filename"
    	end
  		validates :name, :stake, :duration, :start, presence: true
    		validates :stake, numericality: { greater_or_equal: 0 }
          validates :duration, numericality: { greater_than: 0 }
    		#validates_attachment_presence :image > image is optional

  #JQ belongs to HOST - added "has many comments"
    	acts_as_commentable

      belongs_to :user
      has_many :payments
      has_many :comments
      has_many :questions
      
    #:end_date = :start + :duration
  

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy, :get_questions]
  before_filter :authenticate_user!, only: [:host, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  

#JQ I need to re-define this host not just as a current user signed in by higher authority than a regular user

  def host
    @challenges = Challenge.where(user: current_user).order("created_at DESC")
  end

  def player
    @challenges = Challenge.where(user: current_user).order("created_at DESC")
  end

  #def get_questions
    #@questions = Questions.find(params[:questions_id])
    #@challenge = @question.challenge.find(params[:id])
  #end

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8 )
    @comments = Comment.where(commentable_type: "Challenge").find(:all, limit: 15, order: 'created_at DESC')
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    @challenges = Challenge.all

    
    
    #try this one:
    #@challenge=Challenge.all.find(params[:challenge_id])
    #@question = @challenge.question.find(params[:id])

    #@root_comments = @questions.root_comments
    #@comments = @question.root_comments.order('created_at DESC')
    #@new_comment = Comment.build_from(@question, current_user, "")

    #@comments = @question.root_comments.order('created_at DESC')
    #@new_comment = Comment.build_from(@question, current_user, "")
    
    #VERSION FROM GITHUB, THEY USE ARTICLE AS EXAMPLE
    #@challenge = Challenge.find(params[:id])
    #@user_who_commented = @current_user
    #@comment = Comment.build_from( @challenge, @user_who_commented.id, "Hey guys this is my comment!" )
    
    #@questions = @challenge.root_comments
    
    #ALEX chap
    #@challenge = Challenge.all
    #@comments = @challenge.root_comments.order('created_at DESC')
    #@new_comment = Comment.build_from(@challenge, current_user, "")

    #ALEX QUES CONTROL
    
  end


  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    #set user id for challenge to current user
    #set this to HOST ID
    #take user id and assign to host if user created=HOST...else user END
    @challenge.user_id = current_user.id
#create migration: host boolean, true


   

#move this to DEVISE edit user profile.  You don't want users to put in their bank info in the begining of creating a challenge

  
    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.  ADD WEARABLE TECH HERE
    def challenge_params
      params.require(:challenge).permit(:name, :duration, :start, :end, :image, :stake)
    end

    #DELETE THIS AFTER, MAKES NO SENSE FOR FITJAR>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    def check_user
      if current_user != @challenge.user
        redirect_to root_url, alert: "Sorry, only the host may edit this challenges"
      end
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
      <%= form_for(@challenge, :html => { :multipart => true }) do |f| %>
        <% if @challenge.errors.any? %>
          <div id="error_explanation"class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h4>
            <ul>
              <% @challenge.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

             <div id="stripe_error" class="alert alert-danger" style="display:none">
              <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
            </div>
    <br><br>

    <form class="form-horizontal" role="form">
      <div class="container">
<!-- NAME OF CHALLENGE --> 
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-5 control-label" style="text-align: right">Name Your Challenge:</label>
            <div class="col-sm-3">
              <%= f.text_field :name, :placeholder => "Hell Week!", autofocus: true, class: "form-control" %>
            </div>
          </div><br><br>
<!-- WHEN SHALL WE BEGIN --> 
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label" style="text-align: right">When Shall We Begin?</label>
              <div class="col-sm-3">
                <%= f.date_field :start, :placeholder => " mm/dd/yyyy", class: "form-control" %>
              </div>
          </div><br><br>

<!-- DURATION = DATE + 7, 21, OR 30 DAYS --> 
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label" style="text-align: right">Duration:</label>
            <div class="col-sm-3">
                  <div class="btn-group">   
                    <%= f.select(:duration, options_for_select([['7  Days',7], ['21  Days',21], ['30  Days',30]]), {}, {class: "form-control"}) %>
                  </div>
            </div>
          </div><br><br>
<!-- STAKE-->  
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label" style="text-align: right">Stake:</label>
            <div class="col-sm-3">
                  <div class="btn-group">   
                    <%= f.select(:stake, options_for_select([['$0',0], ['$10',10], ['$20',20], ['$50',50], ['$100',100],['Other',0]]), {}, {class: "form-control"}) %>
                  </div>
            </div>
          </div><br><br>
<!-- BUTTON -->     
          <div class="form-group">
              <label for="inputEmail3" class="col-sm-5 control-label" style="text-align: right"></label>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.submit class: "btn btn-primary btn-block" %>
                </div>
              </div>
          </div><br><br>
      </div>  <!--<<<DIV FOR THE CONTAINER -->   
    </form>
<%end%>

app/views/challenges/_form_player.html.erb
      <%= form_for(@challenge, :html => { :multipart => true }) do |f| %>
        <% if @challenge.errors.any? %>
          <div id="error_explanation"class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h4>
            <ul>
              <% @challenge.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

             <div id="stripe_error" class="alert alert-danger" style="display:none">
              <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
            </div>
    <br><br>

    <form class="form-horizontal" role="form">
      <div class="container">
<!-- NAME OF CHALLENGE --> 
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-5 control-label" style="text-align: right">Name Your Challenge:</label>
            <div class="col-sm-3">
              <%= f.text_field :name, :placeholder => "Hell Week!", autofocus: true, class: "form-control" %>
            </div>
          </div><br><br>
<!-- WHEN SHALL WE BEGIN --> 
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label" style="text-align: right">When Shall We Begin?</label>
              <div class="col-sm-3">
                <%= f.date_field :start, :placeholder => " mm/dd/yyyy", class: "form-control" %>
              </div>
          </div><br><br>

<!-- DURATION = DATE + 7, 21, OR 30 DAYS --> 
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label" style="text-align: right">Duration:</label>
            <div class="col-sm-3">
                  <div class="btn-group">   
                    <%= f.select(:duration, options_for_select([['7  Days',7], ['21  Days',21], ['30  Days',30]]), {}, {class: "form-control"}) %>
                  </div>
            </div>
          </div><br><br>
<!-- STAKE-->  
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label" style="text-align: right">Stake:</label>
            <div class="col-sm-3">
                  <div class="btn-group">   
                    <%= f.select(:stake, options_for_select([['$0',0], ['$10',10], ['$20',20], ['$50',50], ['$100',100],['Other',0]]), {}, {class: "form-control"}) %>
                  </div>
            </div>
          </div><br><br>
<!-- BUTTON -->     
          <div class="form-group">
              <label for="inputEmail3" class="col-sm-5 control-label" style="text-align: right"></label>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.submit class: "btn btn-primary btn-block" %>
                </div>
              </div>
          </div><br><br>
      </div>  <!--<<<DIV FOR THE CONTAINER -->   
    </form>
<%end%>

app/views/challenges/_host.html.erb
<!--pregame-->
  
  <table class="table table-bordered">

<div class="center-block">
  <dl class="dl-horizontal">
    <dt><h4> Players Signed Up: </h4></dt>
    <dd><h4> List of Emails....</h4></dd>
    <dt><h4> Who Else Is Game?: </h4></dt>
      <dd>
        <div class="col-xs-4">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="john@gmail.com">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Invite</button>

             
            </span>
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </dd>

     <dt><h4> Challenge Amount: </h4></dt>
      <dd>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            Dropdown
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="$50">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">$25</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">$50</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">$75</a></li>
             <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Other</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
          </ul>
        </div>

        <div class="input-group">
          <span class="input-group-addon">$</span>
          <input type="text" class="form-control">
          <span class="input-group-addon">.00</span>
        </div>

      </dd>

        <dt><h4> Change of Plans: </h4></dt>
          <dd>
            <div class="col-xs-2"><input type="text" class="form-control" placeholder="Date">
            </div>
            <i class ="glyphicon glyphicon-calendar"></i>
          </dd>
          <dt><h4> Device:</h4></dt>
  </dl>
</div>
  
  </table>

app/views/challenges/_payment.html.erb
 

      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
          

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>

app/views/challenges/edit.html.erb
<div class="container">
	<h1 class = "center">Edit Your Challenge JQ - host only</h1><br>

	<%= render 'form' %>
	
	 <ul class= "pager">
           <li class="previous"><%= link_to "&larr; Back".html_safe, challenges_path %></li>
           
      </ul>
</div>

app/views/challenges/index.html.erb
<div class="container">
  <div class="center">
  <h1>WELCOME TO THE CHALLENGES ARENA</h1>
  <h2>Choose a Challenge or host your own!</h2>
  </div>

<br>
<br>
<br>


  <div class="center">
    <div class="row">
      <% @challenges.each do |challenge| %>
        <div class="col-md-3">
          <div class="thumbnail">
            <%= link_to image_tag(challenge.image.url), challenge %>
            <div class="caption">
              <h3><%= challenge.name %></h3>
               <h3><%= number_to_currency(challenge.stake) %></h3>
               <!--switch this to button after-->
              <h3><%= "Hosted by #{challenge.user.user_name}" %></h3>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<br>
<br>
<br>
  <br>
  <!--switch this to button after-->
  <h1><div class="container" style="max-width:400px; margin: 0 auto 10px;">
    <div class="center-block">
      <% if user_signed_in? %>
        <div class="center">
          <%= link_to new_challenge_path, class: "btn btn-primary btn-block ", data: {no_turbolink: true} do %>
          <i class ="glyphicon glyphicon-plus"></i> NEW CHALLENGE
          <%end%>
      <%end%>
         </div></h1>
    </div>
  </div>
<br>
<br>
<br>
<br>
    <div class="center">
    <%= will_paginate @posts,renderer: BootstrapPagination::Rails %>
     </div>
      <%#= link_to 'New challenge', new_challenge_path, class: "btn btn-primary", data: { no_turbolink: true } %>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53beb3c6683d863d"></script>

app/views/challenges/new.html.erb
<div class="container"> 
	<br>
	<h1 class = "center">CREATE A NEW FITNESS CHALLENGE</h1>

	<%= render 'form' %>


	  <ul class= "pager">
           <li class="previous"><%= link_to "&larr; Back".html_safe, challenges_path %></li>
      </ul>
</div>

app/views/challenges/new_player.html.erb
<div class="container"> 
	<br>
	<h1 class = "center">CREATE A NEW FITNESS CHALLENGE</h1>

	<%= render 'form/_player' %>


	  <ul class= "pager">
           <li class="previous"><%= link_to "&larr; Back".html_safe, challenges_path %></li>
      </ul>
</div>

app/views/challenges/show.html.erb
<br><br><br>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="thumbnail">
          <%= image_tag @challenge.image.url %>
        </div>
      </div>
      
      <div class="col-md-8">
        <h2 class="center"><%= @challenge.name %> Challenge</h2><br>
          <p>Your host <%= @challenge.user.user_name %>, has set the stage for the challenge below.  Click here to read more about the<button class="btn btn-link" data-toggle="modal" data-target="#myModal">
                  rules
                </button>



                <!-- Modal for RULES -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Rules</h4>
                      </div>
                      <div class="modal-body">
                        <%= render 'pages/rulesPartial' %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>

              <ul>
                <li>DESCRIPTION: <%= @challenge.description %></li>
                <li>STAKE: <%= number_to_currency(@challenge.stake) %></li>
                <li>DURATION: <%= @challenge.duration %></li>
                <li>START DATE: <%= @challenge.start %></li>
                <li>END DATE: <%#= @challenge.end %></li>
              </ul>
          </p>  
  
          <div class="container" style="max-width:400px; margin: 0 auto 10px;">
            <div class="center-block">
              <%= link_to "ACCEPT CHALLENGE", new_challenge_payment_path(@challenge), class: "btn btn-primary  btn-block", data: { no_turbolink: true } %>
             </div>

             <!-- Small modal -->
              <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">DEVICE</button>

              <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                      <div class="form-group">
                          <form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
                          
                      </div>
                  </div>
                </div>
              </div>
             <div class="center-block">
                 <%= form_tag charges_path do %>
                    <article>
                      <label class="amount">
                        <span>Amount: $5.00</span>
                      </label>
                    </article>

                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="A month's subscription"
                            data-amount="3000"></script>
                  <% end %>
             </div>

             
          </div>
      </div>
  </div>



<br><br><br>
 

<!--<%# if @payment == true %>-->
  
      <div class="well">

        <div class="row">
          <div class="col-xs-6 col-md-4"><h4>Challenge Name: <%= @challenge.name %><br><br>Host: <%= @challenge.user.user_name %><br><br>Last Sync:<br></h4></li>
          </div>
          <div class="col-xs-6 col-md-4"><h2><%= number_to_currency(@challenge.stake) %></h2><h4>JAR Amount <br></h4>
          </div>
          <div class="col-xs-6 col-md-4"><h4>Start In</h4>
          </div>
        </div>
     </div>


        <div class="row">
          <h1> LEADERBOARD </h1>
          <div class="col-xs-12 col-md-8">
            
                <div class="progress">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                <span class="sr-only">40% Complete (success)</span>
              </div>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                <span class="sr-only">20% Complete</span>
              </div>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                <span class="sr-only">60% Complete (warning)</span>
              </div>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                <span class="sr-only">80% Complete</span>
              </div>
            </div>
          </div>
        
            <div class="col-xs-6 col-md-4">
                <div class="panel-group" id="accordion">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                           How We Doin?
                        </a>
                      </h3>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                      <div class="panel-body">
                       <p>survey Monkey here</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

  <div class="center"></div>
      <!--JQ - this turbo link must be disabled, else the token won't process-->
      <br>
       <br>
      <ul class= "pager">
           <li class="previous"><%= link_to "&larr; Back".html_safe, challenges_path %></li>
           <li><%= link_to 'Edit', edit_challenge_path(@challenge)%></li>
      </ul>
    </div>
  </div>
<!--<%# else %>-->
<!--<%# end %>-->
<br>



</div>



    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>