config/routes.rb
Fitjar::Application.routes.draw do
  
  get "withdraws/new_release" => 'withdraws#new_release', :as => :new_release

  resources :banks do
  resources :withdraws

end

  resources :devices
  resources :charges

authenticated :user do
  root :to => "challenges#index"
end
unauthenticated :user do
  devise_scope :user do 
    get "/" => "pages#home"
  end
end

  devise_for :users
  resources :challenges do
    resources :questions, except: [:show, :index]
    resources :comments, :only => [:create, :destroy]

    resources :payments, only: [:new, :create]
  end

  get 'faq' => 'pages#faq'
  get 'about' => 'pages#about'
  get 'challenges' => 'challenges#index'
  get 'rules' => 'pages#rules'
  get 'home' => 'pages#home'
  get 'host' => "challenges#host"
  get 'terms' => "pages#terms"
  get 'history' => "payments#history"

end

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=636807976338131&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
	<div class="container">
		<div class="row-fluid center">
			<ul class="list-inline left">
				
				<li><%= link_to "About Us", about_path %></li>|
				<li><%= link_to "FAQ", faq_path %></li>|
				<li><%= link_to "Rules", rules_path %></li>|
				<li><%= link_to "Terms & Privacy", terms_path %></li>|
				<li><%= mail_to "hello@fitjar.co" do %>
					  Contact
					<% end %></li>
				
			</ul>
		</div>	

		<div class="row-fluid center">
			<ul class="list-inline left">
				<li><%= link_to image_tag("https://dl.dropboxusercontent.com/s/qbdm2echj8jxnxq/twitter.png?m="), "http://www.twitter.com/theFITJAR",:target => '_blank'%></li>
				<li><%= link_to image_tag("https://dl.dropboxusercontent.com/s/wwz0yo8f9iqhv1b/facebook.png"), "https://www.facebook.com/theFITJAR" ,:target => '_blank'%></li>
				<li></li>
			</ul>
		</div>	

		<div class="row-fluid center">
			<ul class="list-inline left">
			<li>© 2014 VICEJAR LLC</li>
			</ul>
		</div>	
			
	</div>
</footer>

app/views/layouts/_head.html.erb
   <title>FITJAR Challenge: Get Paid For Getting Fit with Friends, Powered by FitBit, Jawbone Up, Nike+ FuelBand, Basis</title>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        
        <meta name="keywords" content="keywords" />
        <meta name="description" content=" Take our 7 day fitness challenge and get fit and get paid.  Use your favorite wearable fitness tracker and burn calories for cash."/>
		<link rel="shortcut icon" href="images/fav.ico" />

 <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
  
<link href='http://fonts.googleapis.com/css?family=Oswald:300,400,700' rel='stylesheet' type='text/css'>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="https://dl.dropboxusercontent.com/s/u51prm6l5n6wzbi/Logo-Jar.jpg"></a>
      <ul><a class="navbar-brand" href="/home">FITJAR</a></ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">     
      <% if user_signed_in? %>  
        <li><%= link_to "CHALLENGES", challenges_path %></li>

        <% if user_signed_in? %>  
            <li><a href="/banks/new">ACCOUNT <span class="badge">$42</span></a></li>
            <li class="dropdown">
        <% else %>
            <li><a href="/banks">ACCOUNT <span class="badge">$42</span></a></li>
            <li class="dropdown">
        <% end %>

          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.user_name.upcase  %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="active"><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
        </li>
      <% else %>
         
          <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
     </div>
  <!--</div> /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <%= render 'layouts/head' %>
  </head>

  <body>
 
    
      <%= render 'layouts/facebook' %>
  
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable center">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= render 'layouts/header' %>
     <div class="container">
      
    </div>
    
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>